name: "CI"
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        id: checkout_release
        uses: actions/checkout@v3
      - name: Install dependencies
        id: install_deps
        shell: bash
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends gnuplot
      - name: Run tests
        id: run_tests
        shell: bash
        run: .scripts/create_animations_test.sh